<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-9G2HH03" ignored="0" name="Test" tests="11" failures="1" timestamp="21 Sep 2022 06:28:05 GMT" time="0.046" errors="0">
  <testcase name="tc1" time="0.007" classname="AutoUnknown_FailedTc.Demo"/>
  <testcase name="tc2" time="0.002" classname="AutoUnknown_FailedTc.Demo">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.0" classname="AutoUnknown_FailedTc.Demo">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.0" classname="AutoUnknown_FailedTc.Demo">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.001" classname="AutoUnknown_FailedTc.Demo">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.001" classname="AutoUnknown_FailedTc.Demo">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.001" classname="AutoUnknown_FailedTc.Demo">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.0" classname="AutoUnknown_FailedTc.Demo">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.001" classname="AutoUnknown_FailedTc.Demo">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.0" classname="AutoUnknown_FailedTc.Demo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at AutoUnknown_FailedTc.Demo.tc2(Demo.java:15)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase name="tc3" time="0.001" classname="AutoUnknown_FailedTc.Demo"/>
</testsuite> <!-- Test -->
